function B_sym = Bfunfile(q1,q2,q1d,q2d,u1)
%Bfunfile
%    B_sym = Bfunfile(Q1,Q2,Q1D,Q2D,U1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    30-Nov-2025 00:21:46

t2 = cos(q2);
t3 = t2.^2;
t4 = t3.*1.25e+4;
t5 = t4-3.8657e+4;
t6 = 1.0./t5;
B_sym = [0.0;0.0;t6.*-2.9e+4;t6.*(t2.*5.0e+3+5.8e+3).*5.0];
end
