function B_sym = Bfunfile(q1,q2,q1d,q2d,u1)
%Bfunfile
%    B_sym = Bfunfile(Q1,Q2,Q1D,Q2D,U1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    03-Dec-2025 18:58:07

t2 = cos(q2);
t3 = t2.^2;
t4 = t3.*9.025e+3;
t5 = t4-3.2648e+4;
t6 = 1.0./t5;
B_sym = [0.0;0.0;t6.*-1.06e+6;(t6.*(t2.*4.75e+6+5.3e+6))./5.0];
end
